### ISSUE TITLE
除了登录以外，其他API都无法使用

### ISSUE THREAD

**Issue by pboymt** [Himmas/NeteaseMusicApi#2]
### RT，每次执行的时候都没有任何输出……错误提示都没有。

**Comment by kylin-z** [comment]
能给一下具体的调用方式么

**Comment by pboymt** [comment]
就是完全使用test里面的调用方式，直接除了登陆以外，貌似需要用户验证的都不能用……

**Comment by kylin-z** [comment]
额 具体哪几个不能用？

**Comment by pboymt** [comment]
确实不能用的是search和userPlaylists

**Comment by kylin-z** [comment]
我这刚才测了一下这两个也是正常的，希望你提供一下node版本以及调用代码，另外userPlaylists需要传一个用户Id

**Comment by pboymt** [comment]
调用代码是与test中的一模一样的，没有任何修改，操作系统是windows10 14393 用的是node7.1.0，会不会是依赖模块不兼容导致的？

**Comment by kylin-z** [comment]
7.0我要测试一下 我这边是6.2+

**Comment by zqren** [comment]
没代码说个xx

**Comment by zqren** [comment]
亲测，没问题。如果有问题贴代码

**Comment by ruolinxue** [comment]
7.1测了一下也有数据呢。_(:з」∠)_重现不出来了，我怀疑是什么愚蠢的原因，这两个接口内部调用的模块跟别的接口是一样的

**Comment by pboymt** [comment]
楼上说话客气点，都说了完全使用test代码调用，search没有任何返回，我什么都不用贴，建议戴眼镜看timeline

**Comment by kylin-z** [comment]
你直接跑一下test好嘛，我这跟你的版本一样了

**Comment by guchen0305** [comment]
贴代码不就行了，没学过如何提问？

**Comment by pboymt** [comment]
```javascript
"use strict";
/// <reference path="./typings/index.d.ts" />
const neteaseMusicApi_1 = require('neteaseMusicApi');
neteaseMusicApi_1.topPlaylists((list) => {
    console.log('topPlaylists');
    console.log(list);
});
neteaseMusicApi_1.newAlbum((list) => {
    console.log('newAlbum');
    console.log(list);
});
```
用typescript写的，编译后应该没问题才对……

**Comment by kylin-z** [comment]
看着没什么问题 我手边暂时没有typescript的编译环境 
你可以选择 定位到neteaseMusicApi模块的目录 然后 node test/search 来直接跑测试用例
假如测试用例有数据 那么应该是你这边调用的问题 假如没有那么我们再来讨论
我这边模拟了你的环境确实没法重现

**Comment by pboymt** [comment]
album newAlbum topPlaylists artistAlbums userPlsylists comments search在test中全都用不了，没有任何数据或错误返回，dailyRecommend那个文件直接出现TypeError说没有这个方法2333

**Comment by kylin-z** [comment]
dailyRecommend是未完成的api ,只有在readme里面列出来的那几个是可以用的。另外网易的数据如果全部不能获取的话你可以试着换一下网络或者用你电脑上的网易云音乐客户端试一下看看能不能取到数据，有一些局域网是获取不到网易的数据的

**Comment by kylin-z** [comment]
我看你的说明是一会能获取到一会不能的感觉

**Comment by kylin-z** [comment]
如果不兼容或者别的什么问题是会报错的

**Comment by pboymt** [comment]
都试过了，客户端网页端都正常，我尝试修改分析代码吧，我还是比较了解里面的依赖模块的

**Comment by kylin-z** [comment]
好的

**Comment by guchen0305** [comment]
这么了解，自己写一个试试呗

**Comment by pboymt** [comment]
楼上都是大神，了解常用模块不是必须的么？就知道用还有什么说的？

**Comment by pboymt** [comment]
作者们能提供实时交流的方式吗？总是开issue有些不便，还有不少不友善的评论……

**Comment by ruolinxue** [comment]
好的

**Comment by ruolinxue** [comment]
424161163 来群里吧，就是有几个暴脾气的小伙伴，没事儿
