### ISSUE TITLE
加密算法简化

### ISSUE THREAD

**Issue by stkevintan** [Himmas/NeteaseMusicApi#4]
当年写过一个类似项目，对网页端的aes和rsa算法进行了简化，现在看起来还没什么变化。
参考地址： [Cube](https://github.com/stkevintan/Cube/blob/master/src/model/Crypto.js)

**Comment by kylin-z** [comment]
好的我去研究一下

**Comment by stkevintan** [comment]
测试了一下，我的版本还能够正常登陆。
