### ISSUE TITLE
会员歌曲无法播放

### ISSUE THREAD

**Issue by LittleBoy1993** [Himmas/NeteaseMusicApi#5]
搜索会员才可以下载的歌曲，比如 告白气球（周杰伦） 可以得到mp3Url，但是无法得到这个音频资源，打开url返回 404，这个问题作者解决了吗，还是说这样的歌曲就是拿不到资源呢？

**Comment by kylin-z** [comment]
这个是网易云音乐做的版权限制，就是拿不到的

**Comment by LittleBoy1993** [comment]
嗯嗯 感谢了
