### ISSUE TITLE
歌曲都不能播放

### ISSUE THREAD

**Issue by Linbubin** [Himmas/NeteaseMusicApi#6]
不知道是我用的方式不对还是怎么了，拿来的MP3 url直接在网页中输入 都是404，
而且我看了一下，网易云的都是m10打头的，比如
`http://m10.music.126.net/20170728160939/c3747573c9ca184a26ade62f604bf466/ymusic/f491/27f1/4c96/510e0673219af4c8893b32f0a7336441.mp3`

但是作者这个获取到的还是m2开头
`http://m2.music.126.net/AGCE0V3l2cvkfjY7tqZmFA==/3441471399286412.mp3`

是没更新吗？ 还是姿势不对～    其他资源都依然正常

**Comment by kylin-z** [comment]
刚看了一下，这波姿势又被网易云和谐了。。。
